// Generated by scripts/distribution.mjs from packages/archify/browser.mjs — do not edit.
;(() => {
// @spexcode/archify/browser — what a page needs to show renderDiagram()'s SVG inline ([[archify]]): scoped ids and
// the one interaction, focus. No imports: it belongs in a browser bundle, unlike index.mjs. Every state it sets
// is styled by assets/diagram.css.

// @@@scoped ids - every rendered SVG names its markers, grid pattern, title and nodes with the same fixed ids
// (#arrowhead, #grid, …). Two diagrams in one document share one id space, and a url(#arrowhead) resolves to
// the FIRST element with that id — if that copy is hidden (a background tab), the visible diagram loses every
// arrowhead. scopeIds(svgText, prefix) prefixes each id the SVG defines and every reference to one, so each
// inline copy is self-contained. Call it on the text before inserting it.
function scopeIds(svgText, prefix) {
  const ids = new Set([...svgText.matchAll(/\sid="([^"]+)"/g)].map((m) => m[1]));
  const scoped = (id) => (ids.has(id) ? `${prefix}-${id}` : id);
  return svgText
    .replace(/(\sid=")([^"]+)(")/g, (m, a, id, b) => `${a}${scoped(id)}${b}`)
    .replace(/url\(#([^)]+)\)/g, (m, id) => `url(#${scoped(id)})`)
    .replace(/(\s(?:xlink:)?href="#)([^"]+)(")/g, (m, a, id, b) => `${a}${scoped(id)}${b}`)
    .replace(/(\saria-(?:labelledby|describedby)=")([^"]+)(")/g, (m, a, list, b) => `${a}${list.split(/\s+/).map(scoped).join(' ')}${b}`);
}

// focusDiagram(svg, id) focuses the node `id`: the node and its direct neighbours stay lit, everything else
// dims, and each edge touching the node keeps a pulse flowing along it from source to target.
// focusDiagram(svg, null) clears the focus. Returns whether a node was focused.
const SVG_NS = 'http://www.w3.org/2000/svg';
const OVERLAY = 'relationship-pulse-overlay';

function focusDiagram(svg, id) {
  for (const el of svg.querySelectorAll('[data-focus-selected], [data-focus-match]')) {
    el.removeAttribute('data-focus-selected');
    el.removeAttribute('data-focus-match');
  }
  for (const el of svg.querySelectorAll(`.${OVERLAY}`)) el.remove();
  svg.removeAttribute('data-focus-active');
  const byId = (nodeId) => svg.querySelectorAll(`[data-node-id="${CSS.escape(nodeId)}"]`);
  const nodes = id == null ? [] : byId(id);
  if (!nodes.length) return false;

  svg.setAttribute('data-focus-active', 'true');
  for (const node of nodes) node.setAttribute('data-focus-selected', 'true');
  const lit = new Set([id]);
  const overlay = document.createElementNS(SVG_NS, 'g');
  overlay.setAttribute('class', OVERLAY);
  overlay.setAttribute('aria-hidden', 'true');
  const key = CSS.escape(id);
  for (const edge of svg.querySelectorAll(`[data-edge-from="${key}"], [data-edge-to="${key}"]`)) {
    edge.setAttribute('data-focus-match', 'true');
    lit.add(edge.getAttribute('data-edge-from'));
    lit.add(edge.getAttribute('data-edge-to'));
    // The pulse is a bare copy of the edge's line geometry; the viewer draws its relationship pulse the same way.
    const wrap = document.createElementNS(SVG_NS, 'g');
    if (edge.hasAttribute('transform')) wrap.setAttribute('transform', edge.getAttribute('transform'));
    const shapes = /^(path|line|polyline)$/i.test(edge.tagName) ? [edge] : edge.querySelectorAll('path, line, polyline');
    for (const shape of shapes) {
      const pulse = document.createElementNS(SVG_NS, shape.tagName);
      for (const name of ['d', 'points', 'x1', 'y1', 'x2', 'y2']) {
        if (shape.hasAttribute(name)) pulse.setAttribute(name, shape.getAttribute(name));
      }
      pulse.setAttribute('class', 'relationship-flow-pulse');
      pulse.setAttribute('pathLength', '1');
      wrap.append(pulse);
    }
    overlay.append(wrap);
  }
  for (const nodeId of lit) for (const node of byId(nodeId)) node.setAttribute('data-focus-match', 'true');
  svg.append(overlay);
  return true;
}

globalThis.SpexCodeAtlasFocus = { scopeIds, focusDiagram }
})()
